# Generated by Django 2.1.5 on 2019-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.CharField(db_column='companyID', max_length=10, primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, db_column='companyName', max_length=50, null=True)),
                ('preferredemail', models.CharField(blank=True, db_column='preferredEmail', max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectid', models.CharField(db_column='projectID', max_length=5, primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, db_column='startDate', null=True)),
                ('estimatedcompdate', models.DateField(blank=True, db_column='estimatedCompDate', null=True)),
                ('projectname', models.CharField(db_column='projectName', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('updatedate', models.DateTimeField(blank=True, db_column='updateDate', null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('customerid', models.CharField(blank=True, db_column='customerID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Projects',
                'managed': False,
            },
        ),
    ]
